import { cp, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import { dirname, extname, relative, resolve } from "node:path";
import { spawn } from "node:child_process";
import { hostname } from "node:os";
import { env } from "@easysaas/config";
import { writeAudit } from "@easysaas/core";
import { closeDatabase, pool, query, transaction } from "@easysaas/database";
import { createEmailProvider } from "@easysaas/providers";
import ts from "typescript";

type Job={id:string;type:string;payload:Record<string,unknown>;attempts:number;max_attempts:number};
const workerId=`${hostname()}-${process.pid}`; const email=createEmailProvider(); let stopping=false;
const sleep=(ms:number)=>new Promise((r)=>setTimeout(r,ms));
async function command(command:string,args:string[],timeout=600_000):Promise<void>{await new Promise<void>((resolvePromise,reject)=>{const child=spawn(command,args,{cwd:process.cwd(),env:{...process.env},stdio:"inherit",shell:process.platform==="win32"});const timer=setTimeout(()=>{child.kill("SIGTERM");reject(new Error(`Comando excedeu ${timeout} ms.`));},timeout);child.on("error",reject);child.on("exit",(code)=>{clearTimeout(timer);code===0?resolvePromise():reject(new Error(`${command} terminou com código ${code}.`));});});}
async function claim():Promise<Job|undefined>{return transaction(async(client)=>{const result=await client.query<Job>(`SELECT id,type,payload,attempts,max_attempts FROM jobs WHERE status='queued' AND available_at<=now() ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1`);const job=result.rows[0];if(!job)return undefined;await client.query("UPDATE jobs SET status='running',attempts=attempts+1,locked_at=now(),locked_by=$1 WHERE id=$2",[workerId,job.id]);return job;});}
async function activeState():Promise<{modules:Array<{stableId:string;version:string}>}>{try{return JSON.parse(await readFile(resolve(process.cwd(),"runtime/active-modules.json"),"utf8")) as {modules:Array<{stableId:string;version:string}>};}catch{return {modules:[]};}}
async function saveActive(state:{modules:Array<{stableId:string;version:string}>}):Promise<void>{await writeFile(resolve(process.cwd(),"runtime/active-modules.json"),JSON.stringify(state,null,2)+"\n","utf8");}

async function walkFiles(base:string):Promise<string[]>{const out:string[]=[];for(const entry of await readdir(base,{withFileTypes:true})){const path=resolve(base,entry.name);if(entry.isDirectory())out.push(...await walkFiles(path));else out.push(path);}return out;}
async function compileModuleServer(moduleDir:string,stableId:string,manifest:Record<string,unknown>):Promise<void>{const serverFile=typeof manifest.serverFile==="string"?manifest.serverFile:undefined;const target=resolve(process.cwd(),"runtime/module-runtime",stableId);await rm(target,{recursive:true,force:true});if(!serverFile)return;const files=(await walkFiles(moduleDir)).filter((file)=>extname(file)===".ts"&&!file.endsWith(".test.ts")&&!file.endsWith("module.ts"));for(const file of files){const rel=relative(moduleDir,file);const output=resolve(target,rel.replace(/\.ts$/,".js"));await mkdir(dirname(output),{recursive:true});const source=await readFile(file,"utf8");const result=ts.transpileModule(source,{fileName:file,compilerOptions:{target:ts.ScriptTarget.ES2023,module:ts.ModuleKind.ESNext,verbatimModuleSyntax:true},reportDiagnostics:true});const diagnostics=result.diagnostics??[];if(diagnostics.length)throw new Error(diagnostics.map((d)=>ts.flattenDiagnosticMessageText(d.messageText," ")).join("\n"));const code=result.outputText.replace(/(from\s+["'][^"']+)\.ts(["'])/g,"$1.js$2").replace(/(import\(["'][^"']+)\.ts(["']\))/g,"$1.js$2");await writeFile(output,code,"utf8");}}

async function deployModule(job:Job):Promise<void>{
  const moduleId=String(job.payload.moduleId);const versionId=String(job.payload.versionId);const data=await query<{stable_id:string;version:string;storage_path:string;manifest:Record<string,unknown>}>(`SELECT m.stable_id,v.version,v.storage_path,v.manifest FROM module_versions v JOIN app_modules m ON m.id=v.module_id WHERE v.id=$1 AND m.id=$2 AND v.validation_status='passed'`,[versionId,moduleId]);const item=data.rows[0];if(!item)throw new Error("Versão validada não encontrada.");
  const moduleDir=resolve(process.cwd(),"modules",item.stable_id);const candidate=resolve(process.cwd(),"runtime/tmp",`${item.stable_id}-candidate-${Date.now()}`);const backup=resolve(process.cwd(),"runtime/tmp",`${item.stable_id}-previous-${Date.now()}`);const previousState=await activeState();
  await cp(item.storage_path,candidate,{recursive:true,errorOnExist:true});let hadCurrent=false;
  try{await rename(moduleDir,backup);hadCurrent=true;}catch{}
  try{
    await rename(candidate,moduleDir);await compileModuleServer(moduleDir,item.stable_id,item.manifest);const state={modules:[...previousState.modules.filter((m)=>m.stableId!==item.stable_id),{stableId:item.stable_id,version:item.version}]};await saveActive(state);
    await command(process.platform==="win32"?"pnpm.cmd":"pnpm",["modules:registry"],120_000);
    await command(process.platform==="win32"?"pnpm.cmd":"pnpm",["--filter","@easysaas/web","build"],900_000);
    await query("UPDATE module_versions SET activated_at=now(),archived_at=NULL WHERE id=$1",[versionId]);await query("UPDATE module_versions SET archived_at=now() WHERE module_id=$1 AND id<>$2 AND activated_at IS NOT NULL AND archived_at IS NULL",[moduleId,versionId]);await query("UPDATE app_modules SET active_version_id=$1,status='active',visible=true,updated_at=now() WHERE id=$2",[versionId,moduleId]);await query("UPDATE system_settings SET value=jsonb_set(jsonb_set(value,'{version}',to_jsonb(COALESCE((value->>'version')::int,0)+1)),'{reloadRequired}','true'::jsonb),updated_at=now() WHERE key='structure'");await writeFile(resolve(process.cwd(),"runtime/reload.signal"),JSON.stringify({reason:"module-deployed",moduleId,versionId,at:new Date().toISOString()}),"utf8");await rm(backup,{recursive:true,force:true});
    await writeAudit({...(typeof job.payload.requestedBy==="string"?{actorUserId:job.payload.requestedBy}:{}),action:"module.activated",targetType:"module",targetId:moduleId,metadata:{versionId,version:item.version}});
  }catch(error){await rm(moduleDir,{recursive:true,force:true});if(hadCurrent)await rename(backup,moduleDir);await rm(resolve(process.cwd(),"runtime/module-runtime",item.stable_id),{recursive:true,force:true});await saveActive(previousState);await command(process.platform==="win32"?"pnpm.cmd":"pnpm",["modules:registry"],120_000).catch(()=>{});await query("UPDATE app_modules SET status=CASE WHEN active_version_id IS NULL THEN 'failed' ELSE 'active' END,updated_at=now() WHERE id=$1",[moduleId]);throw error;}finally{await rm(candidate,{recursive:true,force:true});}
}
async function archiveModule(job:Job):Promise<void>{const stableId=String(job.payload.stableId);const source=resolve(process.cwd(),"modules",stableId);const target=resolve(process.cwd(),"runtime/module-archive",`${stableId}-${Date.now()}`);await mkdir(dirname(target),{recursive:true});try{await rename(source,target);}catch{}const state=await activeState();await saveActive({modules:state.modules.filter((m)=>m.stableId!==stableId)});await command(process.platform==="win32"?"pnpm.cmd":"pnpm",["modules:registry"]);await command(process.platform==="win32"?"pnpm.cmd":"pnpm",["--filter","@easysaas/web","build"],900_000);await query("UPDATE app_modules SET status='inactive',visible=false,updated_at=now() WHERE id=$1",[String(job.payload.moduleId)]);await writeFile(resolve(process.cwd(),"runtime/reload.signal"),JSON.stringify({reason:"module-archived",stableId,at:new Date().toISOString()}),"utf8");}
async function createBackup(job:Job):Promise<void>{const timestamp=new Date().toISOString().replaceAll(":","-");const dir=resolve(process.cwd(),"runtime/backups",timestamp);await mkdir(dir,{recursive:true});await command("pg_dump",["--format=custom","--file",resolve(dir,"database.dump"),env.databaseUrl],600_000);await cp(resolve(process.cwd(),"runtime/module-store"),resolve(dir,"module-store"),{recursive:true}).catch(()=>{});await cp(resolve(process.cwd(),env.storageLocalPath),resolve(dir,"storage"),{recursive:true}).catch(()=>{});await writeFile(resolve(dir,"manifest.json"),JSON.stringify({createdAt:new Date().toISOString(),jobId:job.id,version:"1.0.0"},null,2));await writeAudit({...(typeof job.payload.requestedBy==="string"?{actorUserId:job.payload.requestedBy}:{}),action:"backup.completed",targetType:"backup",targetId:timestamp});}
async function processJob(job:Job):Promise<void>{if(job.type==="email.send"){await email.send(job.payload as unknown as {to:string;subject:string;text:string;html?:string});return;}if(job.type==="module.deploy")return deployModule(job);if(job.type==="module.archive")return archiveModule(job);if(job.type==="backup.create")return createBackup(job);throw new Error(`Tipo de job desconhecido: ${job.type}`);}
async function loop(){console.log(`[worker] ${workerId} iniciado`);while(!stopping){const job=await claim();if(!job){await sleep(1000);continue;}try{await processJob(job);await query("UPDATE jobs SET status='completed',completed_at=now(),locked_at=NULL,locked_by=NULL WHERE id=$1",[job.id]);}catch(error){const message=error instanceof Error?error.stack??error.message:String(error);const nextAttempts=job.attempts+1;await query(`UPDATE jobs SET status=CASE WHEN $2>=max_attempts THEN 'failed' ELSE 'queued' END,last_error=$3,available_at=now()+(interval '1 minute'*GREATEST(1,$2)),locked_at=NULL,locked_by=NULL WHERE id=$1`,[job.id,nextAttempts,message]);console.error(`[worker] job ${job.id} falhou`,error);}}}
process.on("SIGINT",()=>{stopping=true;});process.on("SIGTERM",()=>{stopping=true;});await loop();await closeDatabase();
