"use client";
import { type FormEvent, useState } from "react";
import { clientApi, errorMessage } from "@/lib/client-api";
type Account={profile:{name:string;email:string;theme:string;locale:string;timezone:string};mfa:Array<{id:string;type:string;label:string;verified_at?:string}>};
type Session={id:string;user_agent?:string;created_at:string;last_seen_at:string;expires_at:string;current:boolean};
export function AccountClient({initial,sessions}:{initial:Account;sessions:Session[]}){const [message,setMessage]=useState("");const [error,setError]=useState("");const [mfaSetup,setMfaSetup]=useState<{credentialId:string;secret:string;uri:string}|null>(null);const [sessionList,setSessions]=useState(sessions);async function action(fn:()=>Promise<unknown>,success:string){setError("");setMessage("");try{await fn();setMessage(success);}catch(e){setError(errorMessage(e));}}
async function profile(event:FormEvent<HTMLFormElement>){event.preventDefault();const d=new FormData(event.currentTarget);await action(()=>clientApi("/api/v1/account",{method:"PATCH",body:JSON.stringify({name:d.get("name"),theme:d.get("theme"),locale:d.get("locale"),timezone:d.get("timezone")})}),"Preferências salvas.");}
async function password(event:FormEvent<HTMLFormElement>){event.preventDefault();const d=new FormData(event.currentTarget);await action(()=>clientApi("/api/v1/account/password",{method:"POST",body:JSON.stringify({currentPassword:d.get("currentPassword"),newPassword:d.get("newPassword")})}),"Senha alterada e outras sessões encerradas.");event.currentTarget.reset();}
async function startMfa(){try{setMfaSetup(await clientApi("/api/v1/account/mfa/totp/start",{method:"POST"}));}catch(e){setError(errorMessage(e));}}
async function confirmMfa(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!mfaSetup)return;const d=new FormData(event.currentTarget);try{const result=await clientApi<{recoveryCodes:string[]}>("/api/v1/account/mfa/totp/confirm",{method:"POST",body:JSON.stringify({credentialId:mfaSetup.credentialId,code:d.get("code")})});setMessage(`MFA ativado. Guarde os códigos: ${result.recoveryCodes.join(" · ")}`);setMfaSetup(null);location.reload();}catch(e){setError(errorMessage(e));}}
async function revoke(id:string){await action(async()=>{await clientApi(`/api/v1/account/sessions/${id}`,{method:"DELETE"});setSessions((v)=>v.filter((s)=>s.id!==id));},"Sessão encerrada.");}
return <div className="settings-grid">{message&&<div className="notice success">{message}</div>}{error&&<div className="notice error">{error}</div>}<section className="panel"><h2>Perfil e preferências</h2><form className="form-stack" onSubmit={profile}><label className="field"><span>Nome</span><input name="name" defaultValue={initial.profile.name}/></label><label className="field"><span>E-mail</span><input value={initial.profile.email} disabled/></label><label className="field"><span>Tema</span><select name="theme" defaultValue={initial.profile.theme}><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Escuro</option></select></label><label className="field"><span>Idioma</span><input name="locale" defaultValue={initial.profile.locale}/></label><label className="field"><span>Fuso horário</span><input name="timezone" defaultValue={initial.profile.timezone}/></label><button className="button button-primary">Salvar</button></form></section><section className="panel"><h2>Alterar senha</h2><form className="form-stack" onSubmit={password}><label className="field"><span>Senha atual</span><input name="currentPassword" type="password" autoComplete="current-password"/></label><label className="field"><span>Nova senha</span><input name="newPassword" type="password" autoComplete="new-password"/></label><button className="button button-secondary">Alterar senha</button></form></section><section className="panel"><h2>Autenticação em duas etapas</h2>{initial.mfa.some((m)=>m.verified_at)?<p className="success-text">MFA está ativado nesta conta.</p>:<><p>Administradores precisam ativar MFA antes de executar ações críticas.</p>{!mfaSetup?<button className="button button-primary" onClick={startMfa}>Configurar aplicativo autenticador</button>:<form className="form-stack" onSubmit={confirmMfa}><div className="secret-box"><small>Chave manual</small><code>{mfaSetup.secret}</code></div><label className="field"><span>Código de 6 dígitos</span><input name="code" inputMode="numeric" pattern="[0-9]{6}"/></label><button className="button button-primary">Confirmar MFA</button></form>}</>}</section><section className="panel panel-wide"><h2>Sessões e dispositivos</h2><div className="table-wrap"><table><thead><tr><th>Dispositivo</th><th>Última atividade</th><th>Expira</th><th></th></tr></thead><tbody>{sessionList.map((s)=><tr key={s.id}><td>{s.user_agent??"Dispositivo desconhecido"}{s.current&&<span className="status-badge">Atual</span>}</td><td>{new Date(s.last_seen_at).toLocaleString("pt-BR")}</td><td>{new Date(s.expires_at).toLocaleString("pt-BR")}</td><td>{!s.current&&<button className="link-button" onClick={()=>revoke(s.id)}>Encerrar</button>}</td></tr>)}</tbody></table></div></section></div>}
