import Link from "next/link";
type Section={id:string;type:string;name:string;content:Record<string,unknown>};
type Landing={company?:{company_name?:string;logo_path?:string};sections:Section[];modules:Array<{stable_id:string;visual_name:string;description:string;icon?:string}>};
const string=(value:unknown,fallback="")=>typeof value==="string"?value:fallback;
const object=(value:unknown)=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
const array=(value:unknown)=>Array.isArray(value)?value:[];
export function PublicLanding({landing}:{landing:Landing}){return <div className="public-site">{landing.sections.map((section)=>{
 const c=section.content;if(section.type==="header"){const button=object(c.button);return <header className="public-header" key={section.id}><Link href="/" className="brand-link"><span className="brand-symbol">E</span><span>{string(c.logoText,landing.company?.company_name??"EasySaaS")}</span></Link><nav>{array(c.links).map((item,index)=>{const link=object(item);return <a key={index} href={string(link.href,"#")}>{string(link.label,"Link")}</a>})}</nav><Link className="button button-primary" href={string(button.href,"/login")}>{string(button.label,"Entrar")}</Link></header>}
 if(section.type==="hero"){const primary=object(c.primary),secondary=object(c.secondary);return <section className="landing-hero" key={section.id}><div className="hero-copy"><p className="eyebrow">{string(c.eyebrow)}</p><h1>{string(c.title)}</h1><p className="lead">{string(c.description)}</p><div className="hero-actions"><Link className="button button-primary" href={string(primary.href,"/login")}>{string(primary.label,"Entrar")}</Link>{string(secondary.label)&&<a className="button button-secondary" href={string(secondary.href,"#")}>{string(secondary.label)}</a>}</div></div><div className="hero-preview"><div className="preview-sidebar"/><div className="preview-content"><span/><span/><span/></div></div></section>}
 if(section.type==="features"){const manual=array(c.items).map(object);const items=string(c.mode)==="automatic"?landing.modules.map((m)=>({title:m.visual_name,description:m.description,icon:m.icon})):manual;return <section id="funcionalidades" className="landing-section" key={section.id}><div className="section-heading"><h2>{string(c.title,"Funcionalidades")}</h2><p>{string(c.description)}</p></div><div className="feature-grid">{items.length?items.map((item,index)=><article className="feature-card" key={index}><span className="feature-icon">{string(item.icon,"◆")}</span><h3>{string(item.title)}</h3><p>{string(item.description)}</p></article>):<article className="feature-card"><h3>Aplicativo preparado</h3><p>As funcionalidades ativas serão exibidas aqui pela administração.</p></article>}</div></section>}
 if(section.type==="benefits"){return <section id="beneficios" className="landing-section muted-section" key={section.id}><div className="section-heading"><h2>{string(c.title)}</h2></div><div className="benefit-grid">{array(c.items).map((item,index)=>{const value=object(item);return <article key={index}><span>{String(index+1).padStart(2,"0")}</span><h3>{string(value.title)}</h3><p>{string(value.description)}</p></article>})}</div></section>}
 if(section.type==="cta"){const button=object(c.button);return <section className="landing-cta" key={section.id}><h2>{string(c.title)}</h2><p>{string(c.description)}</p><Link className="button button-light" href={string(button.href,"/login")}>{string(button.label,"Entrar")}</Link></section>}
 if(section.type==="footer"){return <footer className="public-footer" key={section.id}><div><strong>{landing.company?.company_name??"EasySaaS"}</strong><p>{string(c.description)}</p></div><div>{array(c.links).map((item,index)=>{const link=object(item);return <Link key={index} href={string(link.href,"/")}>{string(link.label)}</Link>})}</div><small>{string(c.copyright,"© {{year}} EasySaaS").replace("{{year}}",String(new Date().getFullYear()))}</small></footer>}return null})}</div>}
