import type { FastifyInstance } from "fastify";
import { writeAudit, slugify } from "@easysaas/core";
import { query, transaction } from "@easysaas/database";
import { assert, booleanValue, jsonBody, ok, optionalText, text } from "../lib/http.js";
import { requirePermission, requirePermissionAndCsrf } from "../services/session.js";

export async function adminAppRoutes(app:FastifyInstance):Promise<void>{
  app.get("/api/v1/admin/categories",{preHandler:requirePermission("categories.read")},async(_request,reply)=>{ const result=await query(`SELECT c.*,COALESCE(json_agg(json_build_object('id',m.id,'stableId',m.stable_id,'name',m.visual_name,'slug',m.slug,'status',m.status,'visible',m.visible,'sortOrder',m.sort_order)) FILTER(WHERE m.id IS NOT NULL),'[]') modules FROM app_categories c LEFT JOIN app_modules m ON m.category_id=c.id GROUP BY c.id ORDER BY c.sort_order,c.name`); return ok(reply,result.rows); });
  app.post("/api/v1/admin/categories",{preHandler:requirePermissionAndCsrf("categories.write")},async(request,reply)=>{ const body=jsonBody(request); const name=text(body.name,"Nome",2,100); const slug=slugify(optionalText(body.slug,80)??name); const mode=text(body.mode??"group","Modo",3,20); assert(["group","direct","index"].includes(mode),400,"INVALID_MODE","Modo de categoria inválido."); const result=await query<{id:string}>("INSERT INTO app_categories(name,slug,description,icon,mode,sort_order,enabled) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id",[name,slug,optionalText(body.description,300)??null,optionalText(body.icon,50)??null,mode,Number(body.sortOrder)||100,booleanValue(body.enabled,true)]); await writeAudit({actorUserId:request.currentUser!.id,action:"category.created",targetType:"category",targetId:result.rows[0]!.id,requestId:request.id}); return ok(reply,{id:result.rows[0]!.id},201); });
  app.put("/api/v1/admin/categories/:id",{preHandler:requirePermissionAndCsrf("categories.write")},async(request,reply)=>{ const id=(request.params as {id:string}).id; const body=jsonBody(request); const current=await query<{slug:string}>("SELECT slug FROM app_categories WHERE id=$1",[id]); assert(current.rows[0],404,"CATEGORY_NOT_FOUND","Categoria não encontrada."); const name=text(body.name,"Nome",2,100); const slug=slugify(optionalText(body.slug,80)??name); const mode=text(body.mode??"group","Modo",3,20); assert(["group","direct","index"].includes(mode),400,"INVALID_MODE","Modo inválido."); await query("UPDATE app_categories SET name=$1,slug=$2,description=$3,icon=$4,mode=$5,sort_order=$6,enabled=$7,direct_module_id=$8,updated_at=now() WHERE id=$9",[name,slug,optionalText(body.description,300)??null,optionalText(body.icon,50)??null,mode,Number(body.sortOrder)||100,booleanValue(body.enabled,true),optionalText(body.directModuleId,100)??null,id]); if(current.rows[0].slug!==slug){ const modules=await query<{id:string;slug:string}>("SELECT id,slug FROM app_modules WHERE category_id=$1",[id]); for(const module of modules.rows) await query("INSERT INTO module_redirects(old_path,module_id) VALUES ($1,$2) ON CONFLICT(old_path) DO UPDATE SET module_id=excluded.module_id",[`/app/${current.rows[0].slug}/${module.slug}`,module.id]); } await writeAudit({actorUserId:request.currentUser!.id,action:"category.updated",targetType:"category",targetId:id,requestId:request.id}); return ok(reply,{updated:true}); });
  app.post("/api/v1/admin/categories/reorder",{preHandler:requirePermissionAndCsrf("categories.write")},async(request,reply)=>{ const body=jsonBody(request); const ids=Array.isArray(body.ids)?body.ids.filter((x):x is string=>typeof x==="string"):[]; await transaction(async(client)=>{for(const [index,id] of ids.entries())await client.query("UPDATE app_categories SET sort_order=$1,updated_at=now() WHERE id=$2",[(index+1)*10,id]);}); return ok(reply,{reordered:true}); });
  app.delete("/api/v1/admin/categories/:id",{preHandler:requirePermissionAndCsrf("categories.write")},async(request,reply)=>{ const id=(request.params as {id:string}).id; const body=jsonBody(request); const action=text(body.action??"unassign","Ação",3,20); const target=optionalText(body.targetCategoryId,100); await transaction(async(client)=>{const count=await client.query<{count:string}>("SELECT count(*)::text count FROM app_modules WHERE category_id=$1",[id]); if(Number(count.rows[0]?.count)){if(action==="move"){assert(target,400,"TARGET_REQUIRED","Informe a categoria de destino.");await client.query("UPDATE app_modules SET category_id=$1,updated_at=now() WHERE category_id=$2",[target,id]);}else if(action==="unassign")await client.query("UPDATE app_modules SET category_id=NULL,visible=false,updated_at=now() WHERE category_id=$1",[id]);else if(action==="disable")await client.query("UPDATE app_modules SET category_id=NULL,status='inactive',visible=false,updated_at=now() WHERE category_id=$1",[id]);else throw new Error("A exclusão conjunta de módulos deve ser feita individualmente por segurança.");}await client.query("DELETE FROM app_categories WHERE id=$1",[id]);}); await writeAudit({actorUserId:request.currentUser!.id,action:"category.deleted",targetType:"category",targetId:id,metadata:{action,target},requestId:request.id}); return ok(reply,{deleted:true}); });
}
