import { createHash } from "node:crypto";
import { createWriteStream } from "node:fs";
import { cp, mkdir, rename, rm, stat } from "node:fs/promises";
import { pipeline } from "node:stream/promises";
import { dirname, resolve } from "node:path";
import type { FastifyInstance } from "fastify";
import { writeAudit, slugify } from "@easysaas/core";
import { query, transaction } from "@easysaas/database";
import { discardStaging, validateModuleArchive } from "@easysaas/validation";
import { assert, booleanValue, jsonBody, ok, optionalText, text } from "../lib/http.js";
import { enqueueJob } from "../services/jobs.js";
import { createModuleScaffold } from "../services/modules.js";
import { requirePermission, requirePermissionAndCsrf } from "../services/session.js";

const coreVersion="1.0.0";
export async function adminModuleRoutes(app:FastifyInstance):Promise<void>{
  app.get("/api/v1/admin/modules",{preHandler:requirePermission("modules.read")},async(_request,reply)=>{ const result=await query(`SELECT m.*,c.name category_name,c.slug category_slug,v.version active_version FROM app_modules m LEFT JOIN app_categories c ON c.id=m.category_id LEFT JOIN module_versions v ON v.id=m.active_version_id ORDER BY COALESCE(c.sort_order,9999),m.sort_order,m.visual_name`); return ok(reply,result.rows); });
  app.get("/api/v1/admin/modules/:id",{preHandler:requirePermission("modules.read")},async(request,reply)=>{ const id=(request.params as {id:string}).id; const module=await query("SELECT m.*,c.name category_name,c.slug category_slug FROM app_modules m LEFT JOIN app_categories c ON c.id=m.category_id WHERE m.id=$1",[id]); assert(module.rows[0],404,"MODULE_NOT_FOUND","Módulo não encontrado."); const versions=await query("SELECT id,version,source_hash,validation_status,validation_report,installed_at,activated_at,archived_at FROM module_versions WHERE module_id=$1 ORDER BY installed_at DESC",[id]); const validations=await query("SELECT id,status,stages,errors,started_at,finished_at FROM module_validation_runs WHERE module_id=$1 ORDER BY started_at DESC LIMIT 20",[id]); return ok(reply,{module:module.rows[0],versions:versions.rows,validations:validations.rows}); });
  app.post("/api/v1/admin/modules",{preHandler:requirePermissionAndCsrf("modules.write")},async(request,reply)=>{
    const body=jsonBody(request); const name=text(body.name,"Nome",2,100); const stableId=slugify(optionalText(body.stableId,80)??name); assert(stableId.length>1,400,"INVALID_STABLE_ID","Identificador inválido."); const slug=slugify(optionalText(body.slug,80)??name); const description=optionalText(body.description,500)??"Módulo em implementação.";
    const result=await query<{id:string}>("INSERT INTO app_modules(stable_id,visual_name,slug,description,function_summary,icon,category_id,sort_order,status,visible) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'scaffolded',false) RETURNING id",[stableId,name,slug,description,optionalText(body.functionSummary,500)??null,optionalText(body.icon,50)??null,optionalText(body.categoryId,100)??null,Number(body.sortOrder)||100]);
    try{await createModuleScaffold({stableId,name,description});}catch(error){await query("DELETE FROM app_modules WHERE id=$1",[result.rows[0]!.id]);throw error;}
    await writeAudit({actorUserId:request.currentUser!.id,action:"module.scaffolded",targetType:"module",targetId:result.rows[0]!.id,metadata:{stableId},requestId:request.id}); return ok(reply,{id:result.rows[0]!.id,stableId,status:"scaffolded"},201);
  });
  app.put("/api/v1/admin/modules/:id",{preHandler:requirePermissionAndCsrf("modules.write")},async(request,reply)=>{ const id=(request.params as {id:string}).id; const body=jsonBody(request); const current=await query<{slug:string;category_slug:string|null}>("SELECT m.slug,c.slug category_slug FROM app_modules m LEFT JOIN app_categories c ON c.id=m.category_id WHERE m.id=$1",[id]); assert(current.rows[0],404,"MODULE_NOT_FOUND","Módulo não encontrado."); const name=text(body.name,"Nome",2,100); const slug=slugify(optionalText(body.slug,80)??name); const categoryId=optionalText(body.categoryId,100); if(current.rows[0].category_slug&&(current.rows[0].slug!==slug||categoryId)){await query("INSERT INTO module_redirects(old_path,module_id) VALUES ($1,$2) ON CONFLICT(old_path) DO UPDATE SET module_id=excluded.module_id",[`/app/${current.rows[0].category_slug}/${current.rows[0].slug}`,id]);} await query("UPDATE app_modules SET visual_name=$1,slug=$2,description=$3,function_summary=$4,icon=$5,category_id=$6,sort_order=$7,visible=$8,updated_at=now() WHERE id=$9",[name,slug,optionalText(body.description,500)??"",optionalText(body.functionSummary,500)??null,optionalText(body.icon,50)??null,categoryId??null,Number(body.sortOrder)||100,booleanValue(body.visible,false),id]); await writeAudit({actorUserId:request.currentUser!.id,action:"module.metadata.updated",targetType:"module",targetId:id,requestId:request.id}); return ok(reply,{updated:true}); });
  app.post("/api/v1/admin/modules/:id/upload",{preHandler:requirePermissionAndCsrf("modules.write")},async(request,reply)=>{
    const id=(request.params as {id:string}).id; const module=await query<{stable_id:string}>("SELECT stable_id FROM app_modules WHERE id=$1",[id]); assert(module.rows[0],404,"MODULE_NOT_FOUND","Módulo não encontrado."); const part=await request.file(); assert(part,400,"FILE_REQUIRED","Selecione um pacote ZIP."); assert(part.mimetype==="application/zip"||part.filename.toLowerCase().endsWith(".zip"),400,"INVALID_FILE_TYPE","Envie um arquivo ZIP.");
    const uploadPath=resolve(process.cwd(),"runtime/tmp",`${Date.now()}-${Math.random().toString(16).slice(2)}.zip`); await mkdir(dirname(uploadPath),{recursive:true}); await pipeline(part.file,createWriteStream(uploadPath,{flags:"wx"}));
    const run=await query<{id:string}>("INSERT INTO module_validation_runs(module_id,upload_name,status) VALUES ($1,$2,'running') RETURNING id",[id,part.filename]); const validation=await validateModuleArchive({archivePath:uploadPath,expectedStableId:module.rows[0].stable_id,coreVersion});
    await query("UPDATE module_validation_runs SET upload_hash=$1,status=$2,stages=$3::jsonb,errors=$4::jsonb,finished_at=now() WHERE id=$5",[validation.uploadHash,validation.ok?"passed":"failed",JSON.stringify(validation.stages),JSON.stringify(validation.errors),run.rows[0]!.id]); await rm(uploadPath,{force:true});
    if(!validation.ok||!validation.manifest){await discardStaging(validation.stagingPath);await query("UPDATE app_modules SET status='failed',updated_at=now() WHERE id=$1 AND active_version_id IS NULL",[id]);return reply.status(422).send({error:{code:"MODULE_VALIDATION_FAILED",message:"O módulo foi reprovado.",requestId:request.id,details:{stages:validation.stages,errors:validation.errors}}});}
    const versionPath=resolve(process.cwd(),"runtime/module-store",module.rows[0].stable_id,validation.manifest.version); await mkdir(dirname(versionPath),{recursive:true}); try{await rename(validation.stagingPath,versionPath);}catch{await cp(validation.stagingPath,versionPath,{recursive:true,errorOnExist:true});await discardStaging(validation.stagingPath);}
    const version=await query<{id:string}>("INSERT INTO module_versions(module_id,version,storage_path,source_hash,manifest,validation_status,validation_report,installed_by) VALUES ($1,$2,$3,$4,$5::jsonb,'passed',$6::jsonb,$7) RETURNING id",[id,validation.manifest.version,versionPath,validation.uploadHash,JSON.stringify(validation.manifest),JSON.stringify({stages:validation.stages,fileCount:validation.fileCount,extractedBytes:validation.extractedBytes}),request.currentUser!.id]); await query("UPDATE app_modules SET manifest=$1::jsonb,status='ready',updated_at=now() WHERE id=$2",[JSON.stringify(validation.manifest),id]);
    await writeAudit({actorUserId:request.currentUser!.id,action:"module.version.validated",targetType:"module_version",targetId:version.rows[0]!.id,metadata:{moduleId:id,version:validation.manifest.version},requestId:request.id}); return ok(reply,{versionId:version.rows[0]!.id,status:"ready",manifest:validation.manifest,validation:validation.stages},201);
  });
  app.post("/api/v1/admin/modules/:id/activate",{preHandler:requirePermissionAndCsrf("modules.activate")},async(request,reply)=>{ const id=(request.params as {id:string}).id; const body=jsonBody(request); const versionId=text(body.versionId,"Versão",10,100); const exists=await query("SELECT 1 FROM module_versions WHERE id=$1 AND module_id=$2 AND validation_status='passed'",[versionId,id]); assert(exists.rowCount,404,"VERSION_NOT_FOUND","Versão validada não encontrada."); const jobId=await enqueueJob("module.deploy",{moduleId:id,versionId,requestedBy:request.currentUser!.id}); await query("UPDATE app_modules SET status='validating',updated_at=now() WHERE id=$1",[id]); await writeAudit({actorUserId:request.currentUser!.id,action:"module.activation.requested",targetType:"module",targetId:id,metadata:{versionId,jobId},requestId:request.id}); return ok(reply,{jobId,status:"queued"},202); });
  app.post("/api/v1/admin/modules/:id/deactivate",{preHandler:requirePermissionAndCsrf("modules.activate")},async(request,reply)=>{ const id=(request.params as {id:string}).id; await query("UPDATE app_modules SET status='inactive',visible=false,updated_at=now() WHERE id=$1",[id]); await query("UPDATE system_settings SET value=jsonb_set(value,'{version}',to_jsonb(COALESCE((value->>'version')::int,0)+1)),updated_at=now() WHERE key='structure'"); await writeAudit({actorUserId:request.currentUser!.id,action:"module.deactivated",targetType:"module",targetId:id,requestId:request.id}); return ok(reply,{deactivated:true}); });
  app.post("/api/v1/admin/modules/:id/rollback",{preHandler:requirePermissionAndCsrf("modules.activate")},async(request,reply)=>{ const id=(request.params as {id:string}).id; const body=jsonBody(request); const versionId=text(body.versionId,"Versão",10,100); const jobId=await enqueueJob("module.deploy",{moduleId:id,versionId,requestedBy:request.currentUser!.id,rollback:true}); return ok(reply,{jobId,status:"queued"},202); });
  app.delete("/api/v1/admin/modules/:id",{preHandler:requirePermissionAndCsrf("modules.write")},async(request,reply)=>{ const id=(request.params as {id:string}).id; const module=await query<{stable_id:string}>("SELECT stable_id FROM app_modules WHERE id=$1",[id]); assert(module.rows[0],404,"MODULE_NOT_FOUND","Módulo não encontrado."); await query("UPDATE app_modules SET status='inactive',visible=false,updated_at=now() WHERE id=$1",[id]); const jobId=await enqueueJob("module.archive",{moduleId:id,stableId:module.rows[0].stable_id,requestedBy:request.currentUser!.id}); await writeAudit({actorUserId:request.currentUser!.id,action:"module.deletion.requested",targetType:"module",targetId:id,metadata:{jobId},requestId:request.id}); return ok(reply,{jobId,status:"queued"},202); });
}
