import type { FastifyInstance } from "fastify";
import { writeAudit } from "@easysaas/core";
import { query, transaction } from "@easysaas/database";
import { assert, booleanValue, jsonBody, ok, text } from "../lib/http.js";
import { requirePermission, requirePermissionAndCsrf } from "../services/session.js";

async function snapshot(){const page=(await query("SELECT enabled,status,seo FROM landing_pages WHERE id=true")).rows[0];const sections=(await query("SELECT id,type,name,enabled,sort_order,content FROM landing_sections ORDER BY sort_order")).rows;return {page,sections};}
export async function adminLandingRoutes(app:FastifyInstance):Promise<void>{
  app.get("/api/v1/admin/landing",{preHandler:requirePermission("landing.read")},async(_request,reply)=>ok(reply,await snapshot()));
  app.put("/api/v1/admin/landing/settings",{preHandler:requirePermissionAndCsrf("landing.write")},async(request,reply)=>{const body=jsonBody(request);await query("UPDATE landing_pages SET enabled=$1,seo=$2::jsonb,updated_at=now() WHERE id=true",[booleanValue(body.enabled,true),JSON.stringify(body.seo&&typeof body.seo==="object"?body.seo:{})]);await writeAudit({actorUserId:request.currentUser!.id,action:"landing.settings.updated",targetType:"landing",requestId:request.id});return ok(reply,{updated:true});});
  app.put("/api/v1/admin/landing/sections/:id",{preHandler:requirePermissionAndCsrf("landing.write")},async(request,reply)=>{const id=(request.params as {id:string}).id;const body=jsonBody(request);const name=text(body.name,"Nome",2,100);assert(body.content&&typeof body.content==="object",400,"CONTENT_INVALID","Conteúdo inválido.");await query("UPDATE landing_sections SET name=$1,enabled=$2,sort_order=$3,content=$4::jsonb,updated_at=now() WHERE id=$5",[name,booleanValue(body.enabled,true),Number(body.sortOrder)||100,JSON.stringify(body.content),id]);await writeAudit({actorUserId:request.currentUser!.id,action:"landing.section.updated",targetType:"landing_section",targetId:id,requestId:request.id});return ok(reply,{updated:true});});
  app.post("/api/v1/admin/landing/reorder",{preHandler:requirePermissionAndCsrf("landing.write")},async(request,reply)=>{const body=jsonBody(request);const ids=Array.isArray(body.ids)?body.ids.filter((v):v is string=>typeof v==="string"):[];await transaction(async(client)=>{for(const [i,id] of ids.entries())await client.query("UPDATE landing_sections SET sort_order=$1,updated_at=now() WHERE id=$2",[(i+1)*10,id]);});return ok(reply,{reordered:true});});
  app.post("/api/v1/admin/landing/publish",{preHandler:requirePermissionAndCsrf("landing.write")},async(request,reply)=>{const data=await snapshot();const version=await transaction(async(client)=>{const result=await client.query<{id:string}>("INSERT INTO landing_versions(snapshot,created_by) VALUES ($1::jsonb,$2) RETURNING id",[JSON.stringify(data),request.currentUser!.id]);await client.query("UPDATE landing_pages SET status='published',published_version_id=$1,updated_at=now() WHERE id=true",[result.rows[0]!.id]);return result.rows[0]!.id;});await writeAudit({actorUserId:request.currentUser!.id,action:"landing.published",targetType:"landing_version",targetId:version,requestId:request.id});return ok(reply,{published:true,versionId:version});});
  app.get("/api/v1/admin/landing/versions",{preHandler:requirePermission("landing.read")},async(_request,reply)=>{const result=await query("SELECT id,created_at,created_by FROM landing_versions ORDER BY created_at DESC LIMIT 50");return ok(reply,result.rows);});
  app.post("/api/v1/admin/landing/versions/:id/restore",{preHandler:requirePermissionAndCsrf("landing.write")},async(request,reply)=>{const id=(request.params as {id:string}).id;const version=await query<{snapshot:{page:{enabled:boolean;seo:unknown};sections:Array<{id:string;name:string;enabled:boolean;sort_order:number;content:unknown}>}}>("SELECT snapshot FROM landing_versions WHERE id=$1",[id]);assert(version.rows[0],404,"VERSION_NOT_FOUND","Versão não encontrada.");await transaction(async(client)=>{await client.query("UPDATE landing_pages SET enabled=$1,seo=$2::jsonb,status='draft',updated_at=now() WHERE id=true",[version.rows[0]!.snapshot.page.enabled,JSON.stringify(version.rows[0]!.snapshot.page.seo)]);for(const section of version.rows[0]!.snapshot.sections)await client.query("UPDATE landing_sections SET name=$1,enabled=$2,sort_order=$3,content=$4::jsonb,updated_at=now() WHERE id=$5",[section.name,section.enabled,section.sort_order,JSON.stringify(section.content),section.id]);});await writeAudit({actorUserId:request.currentUser!.id,action:"landing.version.restored",targetType:"landing_version",targetId:id,requestId:request.id});return ok(reply,{restored:true,status:"draft"});});
}
