import type { FastifyInstance } from "fastify";
import { env } from "@easysaas/config";
import { writeAudit } from "@easysaas/core";
import { pool, query } from "@easysaas/database";
import { assert, booleanValue, jsonBody, ok, optionalText, text } from "../lib/http.js";
import { enqueueJob } from "../services/jobs.js";
import { requirePermission, requirePermissionAndCsrf } from "../services/session.js";

export async function adminSystemRoutes(app:FastifyInstance):Promise<void>{
  app.get("/api/v1/admin/dashboard",{preHandler:requirePermission("admin.access")},async(_request,reply)=>{const [users,modules,failed,security,jobs,audit]=await Promise.all([query<{count:string}>("SELECT count(*)::text count FROM users WHERE status='active'"),query<{count:string}>("SELECT count(*)::text count FROM app_modules WHERE status='active'"),query<{count:string}>("SELECT count(*)::text count FROM app_modules WHERE status IN ('failed','invalid')"),query<{count:string}>("SELECT count(*)::text count FROM security_events WHERE severity IN ('warning','critical') AND created_at>now()-interval '7 days'"),query<{count:string}>("SELECT count(*)::text count FROM jobs WHERE status IN ('queued','failed')"),query("SELECT action,target_type,target_id,created_at FROM audit_events ORDER BY created_at DESC LIMIT 10")]);return ok(reply,{metrics:{activeUsers:Number(users.rows[0]?.count??0),activeModules:Number(modules.rows[0]?.count??0),moduleErrors:Number(failed.rows[0]?.count??0),securityAlerts:Number(security.rows[0]?.count??0),pendingJobs:Number(jobs.rows[0]?.count??0)},recentActivity:audit.rows});});
  app.get("/api/v1/admin/company",{preHandler:requirePermission("company.read")},async(_request,reply)=>ok(reply,(await query("SELECT * FROM company_settings WHERE id=true")).rows[0]));
  app.put("/api/v1/admin/company",{preHandler:requirePermissionAndCsrf("company.write")},async(request,reply)=>{const b=jsonBody(request);const name=text(b.companyName,"Nome da empresa",2,150);await query("UPDATE company_settings SET company_name=$1,legal_name=$2,document_number=$3,email=$4,phone=$5,address=$6::jsonb,locale=$7,timezone=$8,branding=$9::jsonb,updated_at=now() WHERE id=true",[name,optionalText(b.legalName,200)??null,optionalText(b.documentNumber,50)??null,optionalText(b.email,254)??null,optionalText(b.phone,50)??null,JSON.stringify(b.address&&typeof b.address==="object"?b.address:{}),optionalText(b.locale,20)??"pt-BR",optionalText(b.timezone,80)??"America/Sao_Paulo",JSON.stringify(b.branding&&typeof b.branding==="object"?b.branding:{})]);await writeAudit({actorUserId:request.currentUser!.id,action:"company.updated",targetType:"company",requestId:request.id});return ok(reply,{updated:true});});
  app.get("/api/v1/admin/system",{preHandler:requirePermission("system.read")},async(_request,reply)=>{const settings=await query("SELECT key,value,updated_at FROM system_settings ORDER BY key");return ok(reply,{settings:settings.rows,runtime:{node:process.version,environment:env.nodeEnv,appUrl:env.appUrl,smtpMode:env.smtpMode,storageDriver:env.storageDriver}});});
  app.put("/api/v1/admin/system/settings/:key",{preHandler:requirePermissionAndCsrf("system.write")},async(request,reply)=>{const key=(request.params as {key:string}).key;assert(["security","privacy_policy","terms_of_use"].includes(key),400,"SETTING_PROTECTED","Esta configuração não pode ser alterada por esta rota.");const body=jsonBody(request);assert(body.value&&typeof body.value==="object",400,"VALUE_INVALID","Valor inválido.");await query("INSERT INTO system_settings(key,value) VALUES ($1,$2::jsonb) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=now()",[key,JSON.stringify(body.value)]);await writeAudit({actorUserId:request.currentUser!.id,action:"system.setting.updated",targetType:"system_setting",targetId:key,requestId:request.id});return ok(reply,{updated:true});});
  app.get("/api/v1/admin/jobs",{preHandler:requirePermission("system.read")},async(_request,reply)=>ok(reply,(await query("SELECT id,type,status,attempts,max_attempts,last_error,created_at,completed_at FROM jobs ORDER BY created_at DESC LIMIT 100")).rows));
  app.post("/api/v1/admin/backups",{preHandler:requirePermissionAndCsrf("backups.run")},async(request,reply)=>{const jobId=await enqueueJob("backup.create",{requestedBy:request.currentUser!.id},1);await writeAudit({actorUserId:request.currentUser!.id,action:"backup.requested",targetType:"job",targetId:jobId,requestId:request.id});return ok(reply,{jobId},202);});
  app.get("/api/v1/admin/system/health",{preHandler:requirePermission("system.read")},async(_request,reply)=>{let database="ok";try{await pool.query("SELECT 1");}catch{database="error";}const jobs=(await query<{count:string}>("SELECT count(*)::text count FROM jobs WHERE status='failed' AND created_at>now()-interval '24 hours'")).rows[0];return ok(reply,{database,failedJobs24h:Number(jobs?.count??0),timestamp:new Date().toISOString()});});
}
